version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.dev
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend
    tty: true
    command: 'yarn start'
