version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.dev
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend
    tty: true
    command: 'yarn start'

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.dev
      target: development
    ports:
      - 8080:8080
    volumes:
      - ./backend:/backend
    tty: true
    command: 'sh gradlew bootRun'
